GET http://localhost:7100/movies HTTP/1.1

###

POST http://localhost:7100/ HTTP/1.1
Content-Type: application/json

{
    "id": 123
}

###
Post http://localhost:7100/find HTTP/1.1
Content-Type: application/json

{
    "theatreId": 1000
}