import { ReactNode } from "react";
import Head from "next/head";
import Header from "./Header";

type PropType = {
  children: ReactNode;
};

export default function Layout({ children }: PropType) {
  return (
    <>
      <Head>
        <title>Movie review</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="lg:w-[1100px] lg:mx-auto h-screen">
        <Header />
        {children}
      </main>
    </>
  );
}

{
  /* {movies && movies.map((movie: MovieType, i: number): JSX.Element | undefined => {
          //METHOD 2
          if (movie.poster) { return <Card key={i} movie={movie} /> }
        }
          //METHOD 1
          //  <Card key={i} {...movie} />
        )} */
}
